services:
    postgres_db:
        image: postgres:latest
        environment:
            POSTGRES_USER: p_user
            POSTGRES_PASSWORD: p_password
        ports: 
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./Scripts/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
        networks:
            - app_network

volumes:
    postgres_data:

networks:
    app_network:
        driver: bridge
